### PR TITLE
Get neg sign

### PR DESCRIPTION
**Pull request by lavigad1**
Yo I gotchu bro

### CODE REVIEW

**Comment by CraigWang1** [comment]
Nice - looks good

one minor thing here: https://github.com/lavigad1/maritime_ec_fork/blob/get_neg_sign/src/position_controller.cpp#L7

**Comment by lavigad1** [comment]
Fixed

**Comment by CraigWang1** [comment]
Look good to me

**Comment by lavigad1** [comment]
Yay!

**Pull request merged**
